services:
  mautrix-signal:
    container_name: mautrix-signal
    image: dock.mau.dev/mautrix/signal:latest
    restart: unless-stopped
    ports:
      - "29328:29328"
    volumes:
      - /mnt/ssd/matrix/signal-bridge:/data
    environment:
      - TZ=Europe/Vienna