services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=Europe/Vienna
      - SECRET=${YAMTRACK_SECRET}
      - REDIS_URL=redis://redis:6379
      - PUID=1000
      - PGID=1000
      - REGISTRATION=False
    volumes:
      - /mnt/ssd/yamtrack/db:/yamtrack/db
    ports:
      - "8008:8000"

  redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - /mnt/ssd/yamtrack/redis:/data