services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3005:8080"
    environment:
      - OLLAMA_BASE_URL=
      - ENABLE_OLLAMA_API=False
    volumes:
      - /mnt/ssd/openwebui:/app/backend/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # TODO: add backup strategy