services:
  ersatztv:
    image: ghcr.io/ersatztv/ersatztv:latest
    container_name: ersatztv
    environment:
      - TZ=Europe/Vienna 
    devices:
      - /dev/dri:/dev/dri # for Intel QuickSync Hardware Transcoding
    ports: 
      - "8409:8409"
    volumes:
      - /mnt/ssd/ersatz-tv:/config
      - /mnt/hdd/data:/mnt/hdd/data:ro
    tmpfs:
      - /transcode
    restart: unless-stopped