services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    restart: always
    ports:
      - "127.0.0.1:5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${COUCHDB_PASS}
    volumes:
      - /mnt/ssd/couchdb/data:/opt/couchdb/data
      - /mnt/ssd/couchdb/etc/local.ini:/opt/couchdb/etc/local.d/local.ini
    labels:
      - docker-volume-backup.stop-during-backup=couchdb

  backup:
    image: offen/docker-volume-backup:latest
    container_name: couchdb_backup
    restart: always
    environment:
      - BACKUP_CRON_EXPRESSION=0 4 * * *
      - BACKUP_FILENAME=couchdb-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_RETENTION_DAYS=30
      - TZ=Europe/Zurich
      - BACKUP_STOP_DURING_BACKUP_LABEL=couchdb
    volumes:
      - /mnt/ssd/couchdb/data:/backup/data:ro
      - /mnt/ssd/couchdb/etc/local.ini:/backup/local.ini:ro
      - /mnt/hdd/couchdb_backups:/archive
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"