services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /mnt/ssd/linkwarden/pgdata:/var/lib/postgresql/data
      - /mnt/hdd/linkwarden_backups:/backups
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "ofelia.enabled=true"
      - "ofelia.job-exec.linkwarden-db-backup.schedule=0 30 6 * * *"
      - "ofelia.job-exec.linkwarden-db-backup.command=sh -c \"pg_dump -U postgres postgres > /backups/db_$$(date +%F).sql && find /backups -name 'db_*.sql' -mtime +30 -delete\""
      
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest 
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_DISABLE_REGISTRATION: true
    ports:
      - 4000:3000
    volumes:
      - /mnt/hdd/linkwarden/data:/data/data
      - /mnt/hdd/linkwarden_backups:/backups
    depends_on:
      - postgres
      - meilisearch
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "ofelia.enabled=true"
      # Triggers exactly at 6:30 AM
      - "ofelia.job-exec.linkwarden-data-backup.schedule=0 30 6 * * *"
      - "ofelia.job-exec.linkwarden-data-backup.command=sh -c \"tar -czf /backups/data_$$(date +%F).tar.gz /data/data && find /backups -name 'data_*.tar.gz' -mtime +30 -delete\""
      
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - /mnt/ssd/linkwarden/meili_data:/meili_data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"