services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8070:8080 # qBittorrent Web UI port
    volumes:
      - /mnt/ssd/gluetun:/gluetun
    environment:
      - TZ=Europe/Zurich
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - VPN_INTERFACE=tun0
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=Netherlands
      - PORT_FORWARD_ONLY=true
      - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=normal
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":{{PORT}},\"current_network_interface\":\"{{VPN_INTERFACE}}\",\"random_port\":false,\"upnp\":false}" http://127.0.0.1:8080/api/v2/app/setPreferences'
      - VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" http://127.0.0.1:8080/api/v2/app/setPreferences'
      - UPDATER_PERIOD=480h
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - WEBUI_PORT=8080
    volumes:
      - /mnt/ssd/qbit/config:/config
      - /mnt/hdd/data:/data
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
networks: {}
