services:
  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - /mnt/ssd/apprise/config:/config
    ports:
      - 8060:8000
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"